name: Python ML & Viz CI

on:
  push:
    branches:
      - "Danny/*"
      - "Jiping/*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas matplotlib seaborn scikit-learn jupyter flake8 black nbval

      # ✅ Lint Python code
      - name: Lint Python files
        run: |
          for folder in src notebooks; do
            if [ -d "$folder" ]; then
              flake8 "$folder"
              black --check "$folder"
            fi
          done

      # ✅ Run Jupyter notebooks
      - name: Execute Jupyter notebooks
        run: |
          if [ -d "notebooks" ] && ls notebooks/*.ipynb 1> /dev/null 2>&1; then
            echo "✅ Notebooks found, running nbval..."
            pytest --nbval notebooks/*.ipynb
          else
            echo "⚠️ No notebooks found, skipping nbval step."
          fi